# Generated by Django 6.0.1 on 2026-01-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voornaam', models.CharField(max_length=100, verbose_name='Voornaam auteur')),
                ('achternaam', models.CharField(max_length=100, verbose_name='Achternaam auteur')),
                ('titel', models.CharField(max_length=255, verbose_name='Titel')),
                ('beschrijving', models.TextField(blank=True, verbose_name='Beschrijving')),
                ('taal', models.CharField(blank=True, choices=[('NL', 'Nederlands'), ('ENG', 'English'), ('D', 'Deutsch'), ('', 'Onbekend')], max_length=10, verbose_name='Taal')),
                ('opmerking', models.TextField(blank=True, verbose_name='Opmerking')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Boek',
                'verbose_name_plural': 'Boeken',
                'ordering': ['achternaam', 'voornaam', 'titel'],
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=255, verbose_name='Titel')),
                ('regisseur', models.CharField(max_length=200, verbose_name='Regisseur')),
                ('schrijver', models.CharField(blank=True, max_length=200, verbose_name='Schrijver')),
                ('acteurs', models.TextField(blank=True, verbose_name='Acteurs')),
                ('jaar', models.CharField(blank=True, max_length=10, verbose_name='Jaar')),
                ('beschrijving', models.TextField(blank=True, verbose_name='Beschrijving')),
                ('taal', models.CharField(blank=True, choices=[('NL', 'Nederlands'), ('ENG', 'English'), ('D', 'Deutsch'), ('', 'Onbekend')], max_length=10, verbose_name='Taal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Films',
                'ordering': ['titel'],
            },
        ),
        migrations.CreateModel(
            name='FodmapItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('Granen', 'Granen'), ('Groente', 'Groente'), ('Fruit', 'Fruit'), ('Zuivel', 'Zuivel'), ('Knollen', 'Knollen'), ('Peulvruchten', 'Peulvruchten'), ('Noten en zaden', 'Noten en zaden'), ('Zoetmiddelen', 'Zoetmiddelen'), ('Kruiden en specerijen', 'Kruiden en specerijen')], max_length=50, verbose_name='Categorie')),
                ('naam', models.CharField(max_length=200, verbose_name='Naam')),
                ('groep', models.CharField(max_length=200, verbose_name='FODMAP Groep')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'FODMAP Item',
                'verbose_name_plural': 'FODMAP Items',
                'ordering': ['categorie', 'naam'],
            },
        ),
    ]
