# Generated by Django 6.0 on 2026-01-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('voornaam', models.CharField(max_length=200)),
                ('achternaam', models.CharField(max_length=200)),
                ('beschrijving', models.TextField(blank=True)),
                ('taal', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['achternaam', 'voornaam', 'titel'],
            },
        ),
    ]
